apiVersion: v1
kind: Service
metadata:
  name: demo-docker-service
spec:
  type: NodePort
  selector:
    app: demo-docker
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30036
