{{- if .Values.ingress.enabled }}
{{- $fullName := include "kubeark-demo-upgrade.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className }}
  {{- end }}
{{- end }}
{{- if .Values.ipTarget }}
  {{- $_ := set .Values.ingress.annotations "external-dns.alpha.kubernetes.io/target" .Values.ipTarget }}
{{- end }}
{{- if .Values.ingress.tls }}
  {{- if gt (len .Values.ingress.tls) 0 }}
    {{- $tls := index .Values.ingress.tls 0 }}
    tls:
      - hosts:
          {{- range $tls.hosts }}
          - {{ . | quote }}
          {{- end }}
        secretName: {{ $tls.secretName }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kubeark-demo-upgrade.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if and .Values.ingress.pathType (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
